# .github/workflows/test_action.yaml
name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Exercice 7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
